services:
  redis:
    image: redis:latest
    container_name: iraap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  app:
    build: .
    container_name: iraap-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - /usr/src/app/node_modules 
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    command: pnpm run build
    restart: always

volumes:
  redis-data:
